# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'CortexSwiftly' do
  pod 'DataCortex', :git => 'https://github.com/data-cortex/cortex-ios-sdk.git', :branch => 'jlake-wip'
end

